# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85d425a96055ce3a7c03119301b29ca9c812bf2b63211e43f17794c8955c876a4bbd49be79096d4ca7a30c3806b48ccba9dfdcba84cfe273ae482c93cd64abc

test:
  secret_key_base: 89ece5c9bf02fdb3fb8d35f9be73fd9cff7c80336d38653d22380c6137d4b1f8bc1fb47b4a2c3776ef2c3adaa6dd0291c199addb274dcbbf4205a86e0d1ff1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
